kind: pipeline
type: docker
name: konrness-com-build

steps:
- name: hello-world
  image: alpine
  commands:
  - echo hello
  - echo world

- name: jekyll-build
  image: jekyll/jekyll:2.5.3
  commands:
  - jekyll build
