kind: pipeline
type: docker
name: konrness-com-build

workspace:
  path: /srv/jekyll

steps:
- name: jekyll-build
  image: jekyll/jekyll:2.5.3
  commands:
  - chmod -R 777 /srv/jekyll
  - jekyll build

- name: docker-build
  when:
    branch: master
    event: push
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    image: plugins/docker
    repo: konrness/konrness.com
