kind: pipeline
type: docker
name: konrness-com-build

workspace:
  path: /srv/jekyll

steps:
- name: hello-world
  image: alpine
  commands:
  - pwd
  - ls -ltra

- name: jekyll-build
  image: jekyll/jekyll:2.5.3
  commands:
  - chmod -R 777 /srv/jekyll
  - jekyll build
