kind: pipeline
type: docker
name: konrness-com-build

workspace:
  path: /srv/jekyll

steps:
- name: jekyll-build
  image: jekyll/jekyll:2.5.3
  commands:
  - chmod -R 777 /srv/jekyll
  - jekyll build
  - date +%y.%m.%d-${DRONE_BUILD_NUMBER},latest > .tags
  - cat .tags

- name: docker-publish
  image: plugins/docker  
  when:
    branch: master
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: konrness/konrness.com
